### ISSUE TITLE
Custom parsers with custom directories

### ISSUE THREAD

**Issue by mk-pmb** [alexindigo/configly#52]
I had to debug for quite a while why `configly` would consistently fail to read my yaml config files from my custom directories. I couldn't find info in the Readme on how to use custom directories and custom options together at the same time, so I assumed I could combine the options from the direct config example:

```javascript
var configObj = config({
  parsers: { /* … */ }
});
```

with the the options for new defaults:

```javascript
module.exports = configly.new({
  defaults: {
    directory: [ /* … */ ]
  }, /* … */
});
```

to write my code: 

```javascript
var projCfg = config({
  parsers: { /* … */ },
  directory: [ /* … */ ],
});
```

After reading the source code, I found that currently I'm supposed to write

```javascript
var projCfg = config([ /* directories go here */ ], {
  parsers: { /* … */ },
});
```

… which I find rather inconsistent.
A higher-priority config object should be able to override all options that would be supported in its defaults object.

* Please allow to provide directories in the config object that also defines the parsers.
* Also please document at least one recommended way of how to use custom parsers with custom directories.

**Comment by alexindigo** [comment]
Thank you for your feedback.

Do you mind to elaborate more on your use case?

And to set the background, this is how we're using it:

```
const configly = require('configly');
const yaml     = require('js-yaml');

// will search:
// - shell's `./config` directory
// - app's specific config folder `./app/config`
// app's config will overwrite values in shell's config
const dirs = [ './config', './app/config' ];

// run configly once with inlined modifiers
// and have it as node-cached module
module.exports = configly(dirs, {
  parsers: {
    yaml: (str) => yaml.safeLoad(str)
  }
});
```

Thank you.

PS. As for docs, there are many different examples how to use the library in the [test folder](https://github.com/alexindigo/configly/tree/master/test). There is fine balance between having enough docs and too much docs separate from the code, to maintain it's freshness – test case always stay up to date.

**Comment by alexindigo** [comment]
@mk-pmb Thanks for the details write up.

I'l start from the end.

> The part with "defaults for .new()" is symbolic because I don't understand that feature yet, either. I couldn't find easily (skimming through) find a chapter on what exactly .new does, or an API description. I'd hope it makes a new function
>
> configly.new(defaultOpts) -> function preconfigured([paths, ][localOpts])
>

Yes, it is to create preconfigured, but yet to be executed instance,
the main idea goes like that:

You have company-wide standard on what formats you use in your configs,
maybe, it's JSON5 for json and yaml, or maybe it's just ini.

Then you'd have npm package that exports preconfigured configly with all that options,
then in the individual applications, developers would import that package, instead of using configly directly. And can run it with specific list of directories they want to look into, and maybe occasional extra option on what format to parse.

> that behaves somewhat like configly(paths, mergeOptions(defaultOpts, localOpts))
>
> but that theoriy wouldn't fit the last code example in section "Custom Files", which has parsers inside defaults but files on the same level as defaults, so it's probably not the new default for the files option.

`files` used to specify what files it should pay attention to, like `default` or `config`, and `parsers` describe what parses/format are available, and what extensions to check for, like `default.json`, `default.yaml`, `config.json` and `config.yaml`.


With that out of the way, back to the main question.

_As you can see I love options._ :) Power to developers is my personal motto, in the same time, there is always fine balance between options that empower and options that confuse and make you waste time.

I was thinking to have directories in the options object along with the first argument, since in my world it was the main use case. But if it could be consumed in both places, then it makes it very confusing on what takes the precedence, is it options object or the first argument. And is one replace another or they're combined. And if they're combined in what order. And if there are duplicates, how it's resolved?
So with all that questions, I decided it'd be more straightforward to only allow single way of specifying directories. It's still accepts defaults parameters, but with defaults, it super clear that new values replace what was set as default.

Based on your use case, it looks like you can have custom package that would export new instance with preconfigured parsers.

`@your-company/config`
```
const configly = require('configly');
const yaml = require('js-yaml')

module.exports = configly.new({
  parsers: {
    yaml: function (x) { return yaml.safeLoad(x); },
  }
});
```

and then use it in your app like:

```
const config = require('@your-company/config');
const defaultCfg = require('./default-config.json');
const mergeOpts = require('merge-options');

const cfgDirs = envVarMagic();
  // ^-- returns an array of directory paths

const customCfg = config(cfgDirs);

module.exports = mergeOptions(defaultCfg, customCfg);
```

PS. Said all of that, I am working on the new version with special feature for parsing environment variables, and this conversation convinced me to have it just as a single argument – options object, with directories being property of that object. It feels more natural with all that ES6 syntax sugar :)

Please let me know if you have more questions, concerns or ideas. 

Thank you.

**Comment by mk-pmb** [comment]
Thanks! I'll be looking forward to that new version, and I'm optimistic it will be more intuitive. If not, I'll re-open this ticket. :-)

**Comment by alexindigo** [comment]
@mk-pmb it took me some sweet time :) but it's finally here: https://github.com/alexindigo/configly/releases/tag/v5.0.0

Let me know how it's working for you.

Thank you.

**Comment by mk-pmb** [comment]
Will do, as soon as I have a suitable project. That, however, might take a while.
